# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-2022

steps:
- script: echo Hello, world!
  displayName: '你好，世界！'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'Minecraft'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/src.zip'
    replaceExistingArchive: true

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 
  displayName: '安装Nuget'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '-c Release -o $(Build.BinariesDirectory)'
    workingDirectory: 'Minecraft'
  displayName: '构建项目'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
